[project]
name = "oslwright"
version = "0.1.0"
description = "None"
readme = "README.md"
authors = [{ name = "Developer", email = "foo@example.com" }]
requires-python = ">=3.12"

dependencies = [
    "flet==0.28.3",
    "fletxr==0.1.4",
    "dacite",
    "dataclasses_json",
    "json5",
    "jsonschema",
    "lark",
    "natsort",
    "pyjson5",
    "regex",
    "meson==1.8.*",  # Please use Meson 1.8.* for GStreamer 1.24.*
    "ninja",
    "jinja2-cli",
    "numpy",  # using opencv configuer
    "gitlint",
    "setuptools<81.0.0",
    "markdown",
    "mako",
    "pydevd"
]

[tool.setuptools]
packages = ["app"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
