# Optimization
# set(CPU_BASELINE "AVX2" CACHE STRING "")
set(ENABLE_LTO ON CACHE BOOL "")

# Miscellaneous
set(BUILD_opencv_world OFF CACHE BOOL "")
set(OPENCV_ENABLE_NONFREE OFF CACHE BOOL "")
set(BUILD_CUDA_STUBS OFF CACHE BOOL "")

set(BUILD_TESTS OFF CACHE BOOL "")
set(BUILD_PERF_TESTS OFF CACHE BOOL "")
set(BUILD_DOCS OFF CACHE BOOL "")
set(BUILD_EXAMPLES OFF CACHE BOOL "")

# PNG, JPEG, TIFF, WEBP support
set(WITH_PNG	ON CACHE BOOL "")
set(BUILD_PNG OFF CACHE BOOL "")
set(WITH_JPEG	ON CACHE BOOL "")
set(BUILD_JPEG OFF CACHE BOOL "")
set(WITH_TIFF OFF CACHE BOOL "")
set(BUILD_TIFF OFF CACHE BOOL "")
set(WITH_WEBP ON CACHE BOOL "")
set(BUILD_WEBP OFF CACHE BOOL "")
set(WITH_OPENJPEG OFF CACHE BOOL "")
set(BUILD_OPENJPEG OFF CACHE BOOL "")
set(WITH_JASPER OFF CACHE BOOL "")
set(BUILD_JASPER OFF CACHE BOOL "")
set(WITH_OPENEXR	OFF CACHE BOOL "")
set(BUILD_OPENEXR OFF CACHE BOOL "")

# Library
set(WITH_ZLIB ON CACHE BOOL "")
set(BUILD_ZLIB OFF CACHE BOOL "")
set(WITH_FREETYPE ON CACHE BOOL "")

set(WITH_PROTOBUF ON CACHE BOOL "")
set(BUILD_PROTOBUF OFF CACHE BOOL "")
set(PROTOBUF_UPDATE_FILES ON CACHE BOOL "")

# Language
set(BUILD_JAVA OFF CACHE BOOL "")
set(BUILD_opencv_python2 OFF CACHE BOOL "")
set(BUILD_opencv_python3 OFF CACHE BOOL "")
set(BUILD_opencv_python_bindings_generator OFF CACHE BOOL "")
set(BUILD_opencv_python_tests OFF CACHE BOOL "")
